project_id = "kwnthojndkdcgnvzugjb"

[functions.novapay-checkout]
verify_jwt = false

[functions.novapay-webhook]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = false

[functions.bot-execute]
verify_jwt = false

[functions.evm-bot-execute]
verify_jwt = false

[functions.pumpportal-execute]
verify_jwt = false

[functions.whale-station]
verify_jwt = false